apiVersion: v1
kind: Service
metadata:
  name: url-shortener-backend
  namespace: url-shortener
  labels:
    app: url-shortener-backend
    app.kubernetes.io/name: url-shortener-backend
    app.kubernetes.io/part-of: home-k8s-platform
spec:
  type: ClusterIP
  selector:
    app: url-shortener-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
